// Default PayGate Provider Configurations
// These are used to populate admin settings on first setup

export const DEFAULT_PAYGATE_PROVIDERS = [
  {
    code: "card-multi",
    name: "Multi Provider (Recommended)",
    description: "Automatically selects the best payment provider for your region",
    minAmount: 1,
    maxAmount: null,
    icon: "🌐",
    type: "card",
    provider: "auto",
    isActive: true,
    sortOrder: 1,
    supportedRegions: ["GLOBAL"],
  },
  {
    code: "card-bitnovo",
    name: "Bitnovo",
    description: "Credit/Debit Card - Europe, Latin America (Spain, Portugal, Italy, France, Mexico)",
    minAmount: 10,
    maxAmount: 10000,
    icon: "💳",
    type: "card",
    provider: "bitnovo",
    isActive: true,
    sortOrder: 2,
    supportedRegions: ["EU", "ES", "PT", "IT", "FR", "MX", "LATAM", "US"],
  },
  {
    code: "card-mercuryo",
    name: "Mercuryo",
    description: "Credit/Debit Card - 180+ countries, Apple Pay, Google Pay",
    minAmount: 30,
    maxAmount: 20000,
    icon: "💳",
    type: "card",
    provider: "mercuryo",
    isActive: true,
    sortOrder: 3,
    supportedRegions: ["GLOBAL"],
  },
  {
    code: "card-unlimit",
    name: "Unlimit",
    description: "Credit/Debit Card - 150+ countries, local payment methods",
    minAmount: 10,
    maxAmount: 10000,
    icon: "💳",
    type: "card",
    provider: "unlimit",
    isActive: true,
    sortOrder: 4,
    supportedRegions: ["GLOBAL"],
  },
  {
    code: "card-guardarian",
    name: "Guardarian",
    description: "Credit/Debit Card - 170+ countries, 50+ payment methods, high limits",
    minAmount: 20,
    maxAmount: 500000,
    icon: "💳",
    type: "card",
    provider: "guardarian",
    isActive: true,
    sortOrder: 5,
    supportedRegions: ["GLOBAL"],
  },
  {
    code: "card-wert",
    name: "Wert",
    description: "Credit/Debit Card via Wert - Global coverage",
    minAmount: 50,
    maxAmount: null,
    icon: "💳",
    type: "card",
    provider: "wert",
    isActive: true,
    sortOrder: 6,
    supportedRegions: ["GLOBAL"],
  },
  {
    code: "card-stripe",
    name: "Stripe (USA Only)",
    description: "Credit/Debit Card via Stripe - US customers only",
    minAmount: 2,
    maxAmount: null,
    icon: "💳",
    type: "card",
    provider: "stripe",
    isActive: true,
    sortOrder: 7,
    supportedRegions: ["US"],
  },
  {
    code: "card-transfi",
    name: "Transfi",
    description: "Credit/Debit Card via Transfi - Global coverage",
    minAmount: 70,
    maxAmount: null,
    icon: "💳",
    type: "card",
    provider: "transfi",
    isActive: true,
    sortOrder: 8,
    supportedRegions: ["GLOBAL"],
  },
  {
    code: "card-rampnetwork",
    name: "Ramp Network",
    description: "Credit/Debit Card via Ramp - EU, UK, US",
    minAmount: 4,
    maxAmount: null,
    icon: "💳",
    type: "card",
    provider: "rampnetwork",
    isActive: true,
    sortOrder: 9,
    supportedRegions: ["EU", "UK", "US"],
  },
  {
    code: "bank-sepa",
    name: "SEPA Bank Transfer",
    description: "SEPA Bank Transfer - EU only",
    minAmount: 50,
    maxAmount: null,
    icon: "🏦",
    type: "bank",
    provider: "sepa",
    isActive: true,
    sortOrder: 10,
    supportedRegions: ["EU"],
  },
  {
    code: "bank-ach",
    name: "ACH Bank Transfer",
    description: "ACH Bank Transfer - US only",
    minAmount: 50,
    maxAmount: null,
    icon: "🏦",
    type: "bank",
    provider: "ach",
    isActive: true,
    sortOrder: 11,
    supportedRegions: ["US"],
  },
  {
    code: "crypto-usdt-trc20",
    name: "USDT (TRC20)",
    description: "Tether on Tron Network - Low fees",
    minAmount: 1,
    maxAmount: null,
    icon: "₮",
    type: "crypto",
    provider: "usdt-trc20",
    isActive: true,
    sortOrder: 12,
    supportedRegions: ["GLOBAL"],
  },
  {
    code: "crypto-usdc-polygon",
    name: "USDC (Polygon)",
    description: "USD Coin on Polygon Network - Very low fees",
    minAmount: 1,
    maxAmount: null,
    icon: "₡",
    type: "crypto",
    provider: "usdc-polygon",
    isActive: true,
    sortOrder: 13,
    supportedRegions: ["GLOBAL"],
  },
];

// Helper function to get default provider by code
export function getDefaultProvider(code) {
  return DEFAULT_PAYGATE_PROVIDERS.find((p) => p.code === code);
}

// Helper function to get all active default providers
export function getActiveDefaultProviders() {
  return DEFAULT_PAYGATE_PROVIDERS.filter((p) => p.isActive);
}
